name = "civetpunk"
compatibility_date = "2025-09-16"

[site]
bucket = "web/out"

# No worker entry-point is required for this static site configuration.
# If you intend to add a Worker script, add a top-level `main` field pointing
# to your worker entry (e.g. main = "workers-site/index.js").
